spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hibernate:
    ddl-auto: update

app:
  name: CarSalesSalon
  description: Application for managing car sales
  environment: Development

security:
  login-page: "/login"
  logout-success-url: "/login?logout"



