spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update # Обязательно, чтобы создавать таблицы
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never # Выполняет скрипты data.sql

  h2:
    console:
      enabled: true # Включает консоль H2
      path: /h2-console # Путь к консоли H2

app:
  name: CarSalesSalon
  description: Application for managing car sales
  environment: Development

security:
  login-page: "/login"
  logout-success-url: "/login?logout"

